-- 024_create_notifications.sql
-- Notifications system for volunteers
-- Stores in-app notifications about events, points, rewards, and system updates.
-- Auto-generated by system triggers (e.g. points awarded, event reminders).
-- Seed data provides sample notifications for testing.

CREATE TABLE IF NOT EXISTS notifications (
    id              SERIAL PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           VARCHAR(255) NOT NULL,
    description     TEXT DEFAULT '',
    icon            VARCHAR(50) DEFAULT 'notifications-outline',
    color           VARCHAR(20) DEFAULT '#6366f1',
    is_read         BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id, is_read) WHERE is_read = FALSE;

-- Seed sample notifications for test users
INSERT INTO notifications (user_id, title, description, icon, color, is_read, created_at)
SELECT u.id, 'Welcome to Volunteering Rewards!', 'Thank you for joining. Start browsing events to earn points.', 'happy-outline', '#10b981', FALSE, NOW() - INTERVAL '1 hour'
FROM users u WHERE u.email = 'alice@test.com'
AND NOT EXISTS (SELECT 1 FROM notifications n WHERE n.user_id = u.id AND n.title LIKE 'Welcome%');

INSERT INTO notifications (user_id, title, description, icon, color, is_read, created_at)
SELECT u.id, 'Points Earned!', 'You earned 20 points for attending Beach Cleanup @ East Coast.', 'star-outline', '#f59e0b', FALSE, NOW() - INTERVAL '2 hours'
FROM users u WHERE u.email = 'alice@test.com'
AND NOT EXISTS (SELECT 1 FROM notifications n WHERE n.user_id = u.id AND n.title LIKE 'Points Earned%');

INSERT INTO notifications (user_id, title, description, icon, color, is_read, created_at)
SELECT u.id, 'New Event Added', 'Elderly Morning Walk has been added to upcoming events. Register now!', 'calendar-outline', '#6366f1', TRUE, NOW() - INTERVAL '1 day'
FROM users u WHERE u.email = 'alice@test.com'
AND NOT EXISTS (SELECT 1 FROM notifications n WHERE n.user_id = u.id AND n.title LIKE 'New Event Added%');

INSERT INTO notifications (user_id, title, description, icon, color, is_read, created_at)
SELECT u.id, 'Welcome to Volunteering Rewards!', 'Thank you for joining. Start browsing events to earn points.', 'happy-outline', '#10b981', FALSE, NOW() - INTERVAL '30 minutes'
FROM users u WHERE u.email = 'eve@test.com'
AND NOT EXISTS (SELECT 1 FROM notifications n WHERE n.user_id = u.id AND n.title LIKE 'Welcome%');
